name: Mirror a repository using SSH
on: 
  push:
  schedule:
    - cron: '0 3 * * *'
    - cron: '0 11 * * *'
    - cron: '0 19 * * *'

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1.0.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: 'git@gitee.com:alexander-huang/coolapk-linux.git'
          destination-repo: 'git@github.com:CoolapkLinux/coolapk-linux.git'
