name: build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      PACKAGE_BUILD=lazygit
    steps:
      - uses: actions/checkout@v2
      - name: passing pkgbuild
        id: passpkg
        run: |
          mkdir -p build/${{ PACKAGE_BUILD }}/
          cp -r workfiles/${{ PACKAGE_BUILD }}/PKGBUILD build/${{ PACKAGE_BUILD }}/
      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: 2m/arch-pkgbuild-builder@v1
        with:
          target: 'run'
          pkgname: 'build/${{ PACKAGE_BUILD }}'
          command: `cp -r build/${{ PACKAGE_BUILD }}/*.pkg.tar.zst coolapklinux/x86_64/ && cd coolapklinux/x86_64/ && repo-add coolapk-linux.db.tar.gz ${{ PACKAGE_BUILD }}-*.pkg.tar.zst `
      - name: Upload package
        id: upload
        run: |
          mv pkgbuild/*/*.zst coolapk-linux/x86_64/
          git config --local user.email "w1301511091@hotmail.com"
          git config --local user.name "oganesson0512"
          git add .
          git commit -m "Build" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
