name: list
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Build File
        id: update
        run: |
          for packagename in `ls -AF workfiles |grep '/$' | tr -d '/'`
            do echo -e 'name: ${packagename}\non:\n  schedule:\n    - cron:  '0 0 * * *'\n  workflow_dispatch:\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v2\n      - name: Validate PKGBUILD\n        id: validate-pkgbuild\n        uses: 2m/arch-pkgbuild-builder@v1.16\n        with:\n           target: 'pkgbuild'\n           pkgname: 'workfiles/$packagename/'\n      - name: Upload package\n        id: upload\n        run: |\n          mv workfiles/${packagename}/*.zst coolapk-linux/x86_64/\n          git config --local user.email "w1301511091@hotmail.com"\n          git config --local user.name "oganesson0512"\n          git add .\n          git commit -m "Build" -a\n      - name: Push changes\n        uses: ad-m/github-push-action@master\n        with:\n          github_token: ${{ secrets.GITHUB_TOKEN }}\n          branch: ${{ github.ref }}' > .github/workflows/${packagename}_build.yml
          done
      - name: Upload 
        id: upload
        run: |
          git config --local user.email "w1301511091@hotmail.com"
          git config --local user.name "oganesson0512"
          git add .
          git commit -m "Build" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
